### ISSUE TITLE
Update ../platform/api/storefront to return all approved listings

### ISSUE THREAD

**Issue by tonyalletag** [ozone-development/ozp-rest#87]
As a developer, I would like to use the ../platform/api/storefont api to return all listings in the center so that I could search listing meta data programatically. 

Suggested add a max parameter to the API with a -1 return all approved listings

../platform/api/storefront?max=-1

**Comment by rpokorny** [comment]
What information exactly are you trying to get?  You said "listing meta data" which usually refers to Categories, Types, etc.  IIRC /api/storefront returns Listings, and not "listing meta data".  Did you really mean "listing meta data" or did you just mean listings?  

Assuming that you just meant listings, I think you can get all approved listings using /api/listing/search with no query parameters.  That endpoint, or just /api/listing, would be the more correct place to add an "all listings" functionality than /api/storefront, which is meant specifically as a shortcut to populate the three carousels on the discovery page in one go.

I also an wondering what exactly is meant by "so that I could search listing meta data programatically".  It sounds like the goal here is to do searching/filtering in JavaScript on the client.  I would advise against that as it requires transferring the entire Listing dataset across the wire, first from the db to the app server, and then from there to the browser.  This is why we have always performed searching in the persistence layer in the past.

**Comment by mparizernc** [comment]
Caveat to what Ross said you will have to double check this but I think /api/listing is not available to all users but /api/listing/search is.

**Comment by rpokorny** [comment]
@mparizernc currently that is true, yes.

**Comment by tonyalletag** [comment]
Awesome.  Thank you both for the info I believe ../platform/api/search will meet this request

**Comment by rpokorny** [comment]
>  I believe ../platform/api/search 
It was platform/api/listing/search actually.
